# Generated by Django 5.0.6 on 2024-07-17 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_remove_project_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
    ]
