# Generated by Django 5.0.6 on 2024-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirna_seeker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_forms",
            name="identity",
            field=models.FloatField(blank=True, default=78, null=True),
        ),
        migrations.AlterField(
            model_name="model_forms",
            name="query_cover",
            field=models.FloatField(blank=True, default=78, null=True),
        ),
        migrations.AlterField(
            model_name="model_forms",
            name="size",
            field=models.IntegerField(blank=True, default=21, null=True),
        ),
    ]
