# Generated by Django 5.0.6 on 2024-07-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sirna_seeker", "0002_alter_model_forms_identity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_forms",
            name="run_blast",
            field=models.BooleanField(default=True),
        ),
    ]
