# Generated by Django 5.0.6 on 2024-07-30 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_results", "0017_remove_taskresult_user"),
        ("sirna_seeker", "0003_model_forms_run_blast"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraTaskInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_results.taskresult",
                    ),
                ),
            ],
        ),
    ]
