# Generated by Django 5.0.6 on 2024-07-31 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sirna_seeker", "0004_extrataskinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExtraTaskInfo",
        ),
    ]
