# Generated by Django 5.0.6 on 2025-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sirna_seeker", "0006_model_forms_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_forms",
            name="threshold",
            field=models.FloatField(blank=True, default=0.6, null=True),
        ),
    ]
